parameters:
#    el_hornair_core.example.class: ElHornair\Bundle\CoreBundle\Example

services:
#    el_hornair_core.example:
#        class: %el_hornair_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
